export type AssetNature = "IMMOVABLE" | "MOVABLE" | "NETWORK" | "QUANTITY";

export type AssetMasterClass = {
  code: string;
  name: string;
  natures: AssetNature[];
  subclasses: string[];
};

export type WorkflowMaster = {
  code: string;
  name: string;
  states: string[];
  control: string;
};

export const assetMasterClasses: AssetMasterClass[] = [
  {
    code: "A01",
    name: "Land, sites, and rights",
    natures: ["IMMOVABLE"],
    subclasses: [
      "Owned site or parcel",
      "Leased or licensed site",
      "Right-of-way or easement",
      "Common land or open space",
      "Market or fair ground",
      "Cremation or burial ground",
      "Playground",
      "Plantation or community-forest site",
    ],
  },
  {
    code: "A02",
    name: "Administrative and civic buildings",
    natures: ["IMMOVABLE"],
    subclasses: [
      "Gram Panchayat Bhawan",
      "Block or Janpad office",
      "Zilla Parishad office",
      "Community hall",
      "Citizen-service facility",
      "Records or store building",
      "Inspection or rest facility",
      "Staff quarter",
      "Multipurpose shelter",
    ],
  },
  {
    code: "A03",
    name: "Education and child development",
    natures: ["IMMOVABLE", "MOVABLE"],
    subclasses: [
      "School building",
      "Classroom",
      "School WASH facility",
      "Cooking shed",
      "Hostel",
      "Anganwadi",
      "Library",
      "Laboratory or workshop",
      "Furniture or equipment set",
      "Digital classroom equipment",
    ],
  },
  {
    code: "A04",
    name: "Health, nutrition, and welfare",
    natures: ["IMMOVABLE", "MOVABLE"],
    subclasses: [
      "Sub-health or health facility",
      "Dispensary",
      "Nutrition store",
      "Public-health equipment",
      "Cold-chain equipment",
      "Accessibility asset",
      "Welfare or day-care facility",
      "First-response equipment",
    ],
  },
  {
    code: "A05",
    name: "Drinking-water source and treatment",
    natures: ["IMMOVABLE", "MOVABLE"],
    subclasses: [
      "Borewell or tubewell",
      "Dug well",
      "Spring or intake",
      "Surface-water intake",
      "Infiltration structure",
      "Hand pump",
      "Pump house",
      "Treatment plant",
      "Chlorination unit",
      "Water-quality equipment",
    ],
  },
  {
    code: "A06",
    name: "Water storage and distribution",
    natures: ["IMMOVABLE", "NETWORK", "MOVABLE"],
    subclasses: [
      "Overhead reservoir",
      "Ground reservoir or sump",
      "Storage tank",
      "Rising main",
      "Distribution pipeline",
      "Standpost or tap",
      "Valve or chamber",
      "Water meter",
      "Tanker",
      "Rainwater-harvesting structure",
    ],
  },
  {
    code: "A07",
    name: "Sanitation and waste",
    natures: ["IMMOVABLE", "NETWORK", "MOVABLE"],
    subclasses: [
      "Community or public toilet",
      "Institutional toilet",
      "Faecal-sludge facility",
      "Sewer or drain",
      "Soak or leach pit",
      "Treatment facility",
      "Segregation or material-recovery shed",
      "Compost unit",
      "Collection vehicle or cart",
      "Waste bin",
      "Plastic-waste unit",
      "Greywater asset",
    ],
  },
  {
    code: "A08",
    name: "Roads, bridges, and transport",
    natures: ["NETWORK", "IMMOVABLE", "MOVABLE"],
    subclasses: [
      "Internal road",
      "Approach road",
      "Footpath",
      "Culvert or causeway",
      "Bridge or footbridge",
      "Retaining wall",
      "Bus shelter",
      "Parking or transport stand",
      "Road furniture",
      "Maintenance equipment",
    ],
  },
  {
    code: "A09",
    name: "Drainage, flood, and conservation",
    natures: ["NETWORK", "IMMOVABLE"],
    subclasses: [
      "Storm-water drain",
      "Closed drain",
      "Check or stop dam",
      "Percolation tank",
      "Pond or water body",
      "Contour trench or bund",
      "Gully or gabion work",
      "Watershed work",
      "Embankment",
      "Recharge structure",
    ],
  },
  {
    code: "A10",
    name: "Irrigation and agriculture support",
    natures: ["IMMOVABLE", "NETWORK", "MOVABLE"],
    subclasses: [
      "Canal or channel",
      "Lift irrigation",
      "Irrigation pump",
      "Field channel or outlet",
      "Community machinery",
      "Input store",
      "Processing floor",
      "Nursery",
      "Conservation equipment",
      "Custom-hiring centre",
    ],
  },
  {
    code: "A11",
    name: "Electricity, renewable energy, and lighting",
    natures: ["IMMOVABLE", "NETWORK", "MOVABLE"],
    subclasses: [
      "Streetlight",
      "High-mast light",
      "Solar streetlight",
      "Solar generation system",
      "Inverter or battery",
      "Generator",
      "Distribution equipment",
      "Electrical installation",
      "Charging point",
      "Energy meter or control panel",
    ],
  },
  {
    code: "A12",
    name: "Markets, livelihoods, and production",
    natures: ["IMMOVABLE", "MOVABLE"],
    subclasses: [
      "Rural market or haat",
      "Stall or kiosk",
      "Warehouse or godown",
      "Cold room",
      "Processing or packaging unit",
      "Self-help-group centre",
      "Common facility centre",
      "Weighing or grading equipment",
      "Vending zone",
      "Tourism or craft facility",
    ],
  },
  {
    code: "A13",
    name: "Digital, communication, and office equipment",
    natures: ["MOVABLE"],
    subclasses: [
      "Desktop",
      "Laptop, tablet, or field device",
      "Server or storage",
      "Printer, scanner, or copier",
      "Network equipment",
      "Approved attendance device",
      "Projector or display",
      "CCTV system",
      "UPS",
      "Telephone or radio",
      "Approved software entitlement",
    ],
  },
  {
    code: "A14",
    name: "Furniture, fixtures, and office assets",
    natures: ["MOVABLE", "QUANTITY"],
    subclasses: [
      "Desk or table",
      "Chair or bench",
      "Cabinet or rack",
      "Meeting-room furniture",
      "Fan, cooler, or air conditioner",
      "Appliance",
      "Kitchen equipment",
      "Fire-safety equipment",
      "Signage",
      "Tools or minor equipment",
    ],
  },
  {
    code: "A15",
    name: "Vehicles and mobile equipment",
    natures: ["MOVABLE"],
    subclasses: [
      "Car or jeep",
      "Utility vehicle",
      "Tractor",
      "Trailer",
      "Motorcycle",
      "Bicycle or e-cycle",
      "Emergency vehicle",
      "Waste vehicle",
      "Water tanker",
      "Construction equipment",
      "Boat or special vehicle",
    ],
  },
  {
    code: "A16",
    name: "Parks, sports, culture, and amenities",
    natures: ["IMMOVABLE", "MOVABLE"],
    subclasses: [
      "Park or garden",
      "Sports facility",
      "Gym equipment",
      "Stage or cultural facility",
      "Memorial",
      "Public seating or shelter",
      "Public display",
      "Drinking-water amenity",
      "Ghat",
      "Fencing or gate",
    ],
  },
  {
    code: "A17",
    name: "Natural-resource and environmental assets",
    natures: ["IMMOVABLE", "MOVABLE"],
    subclasses: [
      "Plantation or green belt",
      "Community nursery",
      "Pasture development",
      "Soil-conservation structure",
      "Conservation-site reference",
      "Environmental monitoring equipment",
      "Remediation facility",
      "Watch or fire structure",
    ],
  },
  {
    code: "A18",
    name: "Public safety and disaster management",
    natures: ["IMMOVABLE", "MOVABLE", "QUANTITY"],
    subclasses: [
      "Emergency shelter",
      "Rescue boat or equipment",
      "Emergency communications",
      "First-aid stock",
      "Fire-fighting equipment",
      "Temporary shelter stock",
      "Warning or public-address system",
      "Relief warehouse",
      "Protective stock",
    ],
  },
  {
    code: "A19",
    name: "Housing and community infrastructure",
    natures: ["IMMOVABLE"],
    subclasses: [
      "Panchayat-owned housing or quarter",
      "Authorized beneficiary-record reference",
      "Group or common infrastructure",
      "Housing-site infrastructure",
      "Community shelter",
    ],
  },
  {
    code: "A20",
    name: "Livestock, fisheries, and veterinary",
    natures: ["IMMOVABLE", "MOVABLE"],
    subclasses: [
      "Veterinary facility",
      "Livestock shelter",
      "Fodder bank",
      "Livestock equipment",
      "Fish pond",
      "Hatchery or fisheries infrastructure",
      "Applicable market or slaughter facility",
    ],
  },
  {
    code: "A21",
    name: "Stores, spares, and consumables",
    natures: ["QUANTITY"],
    subclasses: [
      "Maintenance spare",
      "Water or sanitation consumable",
      "Office consumable",
      "Fuel or lubricant",
      "Safety or protective stock",
      "Electrical or plumbing material",
      "Relief material",
    ],
  },
  {
    code: "A22",
    name: "Proposed assets and works in progress",
    natures: ["IMMOVABLE", "NETWORK"],
    subclasses: [
      "Approved, not started",
      "Work in progress",
      "Substantially complete",
      "Completed, pending registration",
      "Suspended or abandoned",
    ],
  },
];

export const workflowMasters: WorkflowMaster[] = [
  [
    "WF01",
    "Asset registration",
    ["DRAFT", "SUBMITTED", "REVIEW", "APPROVED", "PUBLISHED"],
    "Only published assets enter official totals.",
  ],
  [
    "WF02",
    "Master-data change",
    ["DRAFT_CHANGE", "VALIDATED", "IMPACT_REVIEW", "APPROVED", "ACTIVE"],
    "Used values are versioned and retired, never deleted.",
  ],
  [
    "WF03",
    "LGD jurisdiction import",
    [
      "UPLOADED",
      "PARSED",
      "VALIDATED",
      "DIFF_READY",
      "REVIEWED",
      "APPROVED",
      "ACTIVE",
    ],
    "Ambiguous hierarchy changes require reconciliation.",
  ],
  [
    "WF04",
    "Legacy asset import",
    [
      "UPLOADED",
      "PROFILED",
      "MAPPED",
      "VALIDATED",
      "DRY_RUN",
      "RECONCILIATION",
      "APPROVED",
      "IMPORTED",
      "CLOSED",
    ],
    "Rows retain source lineage and control totals.",
  ],
  [
    "WF05",
    "Document intake",
    ["UPLOADED", "SCAN_PENDING", "SCANNING", "AVAILABLE"],
    "Files remain unavailable until scan and access checks pass.",
  ],
  [
    "WF06",
    "Custody assignment",
    ["REQUESTED", "APPROVED", "ACCEPTED", "ACTIVE", "RELEASED"],
    "Prior custody and effective dates remain in history.",
  ],
  [
    "WF07",
    "Permanent transfer",
    [
      "DRAFT",
      "REQUESTED",
      "SOURCE_REVIEW",
      "DESTINATION_REVIEW",
      "APPROVED",
      "RELEASED",
      "RECEIVED",
      "COMPLETED",
    ],
    "Receipt changes custody atomically; ownership is separate.",
  ],
  [
    "WF08",
    "Temporary movement",
    [
      "REQUESTED",
      "APPROVED",
      "CHECKED_OUT",
      "DUE",
      "RETURNED",
      "INSPECTED",
      "CLOSED",
    ],
    "Condition-out and condition-in evidence is retained.",
  ],
  [
    "WF09",
    "Condition assessment",
    ["DRAFT", "SUBMITTED", "REVIEWED", "ACCEPTED"],
    "Accepted assessments are append-only.",
  ],
  [
    "WF10",
    "Maintenance work order",
    [
      "REQUESTED",
      "TRIAGED",
      "APPROVED",
      "ASSIGNED",
      "IN_PROGRESS",
      "COMPLETED",
      "REVIEW",
      "CLOSED",
    ],
    "Costs, downtime, evidence, and next due are recorded.",
  ],
  [
    "WF11",
    "Preventive plan",
    ["DRAFT", "REVIEWED", "APPROVED", "ACTIVE", "PAUSED", "RETIRED"],
    "Plan revisions do not rewrite generated work.",
  ],
  [
    "WF12",
    "Verification campaign",
    [
      "DRAFT",
      "SCOPE_REVIEW",
      "APPROVED",
      "PUBLISHED",
      "IN_PROGRESS",
      "RECONCILIATION",
      "CLOSURE_REVIEW",
      "CLOSED",
    ],
    "The target population and exclusions are frozen.",
  ],
  [
    "WF13",
    "Field visit and sync",
    ["ASSIGNED", "VISIT_DRAFT", "QUEUED", "SUBMITTED", "VALIDATED", "ACCEPTED"],
    "Offline drafts are distinct from submitted visits.",
  ],
  [
    "WF14",
    "Finding reconciliation",
    [
      "OPEN",
      "TRIAGED",
      "ASSIGNED",
      "REVIEW",
      "DECIDED",
      "CORRECTION_PENDING",
      "RESOLVED",
      "CLOSED",
    ],
    "Corrections use the normal asset workflow.",
  ],
  [
    "WF15",
    "Valuation",
    ["DRAFT", "SUBMITTED", "FINANCE_REVIEW", "APPROVED", "RECORDED"],
    "Decimal valuations are append-only.",
  ],
  [
    "WF16",
    "Ownership change",
    ["REQUESTED", "DOCUMENT_REVIEW", "FINANCE_REVIEW", "APPROVED", "EFFECTIVE"],
    "Ownership is not changed through custody transfer.",
  ],
  [
    "WF17",
    "Disposal and condemnation",
    [
      "DRAFT_CASE",
      "TECHNICAL_ASSESSMENT",
      "RECOMMENDED",
      "COMMITTEE_REVIEW",
      "APPROVED",
      "DISPOSITION",
      "EVIDENCE_REVIEW",
      "CLOSED",
    ],
    "The asset retires only at successful closure.",
  ],
  [
    "WF18",
    "Loss or damage incident",
    [
      "REPORTED",
      "VALIDATED",
      "INVESTIGATION",
      "ACTION_APPROVED",
      "RECOVERY_OR_WRITE_OFF",
      "CLOSED",
    ],
    "Legal, insurance, custody, and recovery references remain linked.",
  ],
  [
    "WF19",
    "Access assignment",
    [
      "REQUESTED",
      "OWNER_REVIEW",
      "SECURITY_REVIEW",
      "APPROVED",
      "ACTIVE",
      "EXPIRED_OR_REVOKED",
    ],
    "Assignments are least-privilege, scoped, and effective-dated.",
  ],
  [
    "WF20",
    "Sensitive export",
    [
      "REQUESTED",
      "POLICY_CHECK",
      "APPROVAL",
      "QUEUED",
      "GENERATED",
      "AVAILABLE",
      "EXPIRED",
    ],
    "Fields are allowlisted, redacted, and audited.",
  ],
  [
    "WF21",
    "Integration reconciliation",
    ["READY", "SENT_OR_RECEIVED", "ACKNOWLEDGED", "APPLIED", "RECONCILED"],
    "Retries and replay are idempotent.",
  ],
  [
    "WF22",
    "Service incident",
    [
      "OPEN",
      "ACKNOWLEDGED",
      "ASSIGNED",
      "IN_PROGRESS",
      "RESOLVED",
      "CONFIRMED",
      "CLOSED",
    ],
    "Contract-approved clocks and exclusions determine SLA results.",
  ],
].map(([code, name, states, control]) => ({
  code: code as string,
  name: name as string,
  states: states as string[],
  control: control as string,
}));

export function filterAssetMasterClasses(search: string) {
  const query = search.trim().toLocaleLowerCase("en-IN");
  if (!query) return assetMasterClasses;

  return assetMasterClasses.filter(({ code, name, subclasses }) =>
    [code, name, ...subclasses].some((value) =>
      value.toLocaleLowerCase("en-IN").includes(query)
    )
  );
}
